name: Docker

on:
  schedule:
    - cron: '00 01 * * *'
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: n9org/docker-java-sshd

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: 
          - 11
          - 17

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry
      - name: Log into registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE_VERSION=${{ matrix.java-version }}
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.java-version }}
